src/EcomProject/EcomProject/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

# from products.views import (ProductListView, 
#                             product_list_view,
#                             ProductDetailView,
#                             ProductDetailSlugView,
#                             product_detail_view,
#                             ProductFeaturedDetailedView
#                             )
from .views import home_page, about_page, contact_page 
from accounts.views import login_page, register_page, logout_operation

urlpatterns = [
    path('', home_page, name='home'),
    path('login/', login_page, name='login'),
    path('register/', register_page, name='register'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    #path('cart/', cart_home, name='cart'),
    path('cart/', include(("carts.urls", 'carts'), namespace='cart')),
    path('products/', include(("products.urls", 'products'), namespace='products')),
    path('search/', include(("search.urls", 'search'), namespace='search')),
    # re_path(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailedView.as_view()),
    # path('products-class/', ProductListView.as_view()),     # making class based view as callable
    # path('products-function/', product_list_view),
    # re_path(r'^products-class/(?P<pk>\d+)/$', ProductDetailView.as_view()),     # making class based view as callable
    # re_path(r'^products-class/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # re_path(r'^products-function/(?P<pk>\d+)/$', product_detail_view),
    path('logout/', logout_operation, name='logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/EcomProject/carts/urls.py
from django.urls import path, re_path
from django.views.generic import detail

from .views import (
                    cart_home, 
                    cart_update,
                    checkout_home,
                    ) 
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('update/', cart_update, name='update'),
]

src/EcomProject/products/urls.py
from django.urls import path, re_path
from django.views.generic import detail

from .views import (
                    ProductListView, 
                    ProductDetailSlugView,
                    ) 
app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),     # making class based view as callable
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

src/EcomProject/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<!-- FontAwesome CSS -->
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

src/EcomProject/templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

src/EcomProject/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'products:list' as product_list_url %}
{% url 'logout' as logout_url %}
{% url 'login' as login_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}">{% if brand_name %} {{brand_name}} {% else %}KH eCommerce {% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
          <a class="nav-link" href="{{ contact_url }}">Contact</a>
        </li>
        <li class="nav-item {% if request.path == about_url %}active{% endif %}">
            <a class="nav-link" href="{{ about_url }}">About</a>
        </li>
        <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
            <a class="nav-link" href="{{ product_list_url }}">Products</a>
        </li>
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}"><i class="fas fa-shopping-cart"></i><b><sup> {{ request.session.cart_items_count }}</sup></b></a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
          <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
        {% endif %}
        
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </nav>